server:
  port: 8080
zuul:
   routes:
      subscription-service:
         path: /v1/**
         url: http://subscription-service:8889
      billing-service:
         path: /billing/**
         url: http://billing-service:8890
ribbon:
   eureka:
      enabled: false
