server:
  port: 8080
zuul:
   routes:
      subscriptionservice:
         path: /v1/**
         url: http://subscriptionservice:8889
      billingservice:
         path: /billing/**
         url: http://billingservice:8890    
ribbon:
   eureka:
      enabled: false