version: '2'
services:
  database:
    image: postgres:9.5
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7layer
      POSTGRES_DB: microservicedb
  configserver:
    image: liemmn/dxc-config-server:microservices
    ports:
    - 8888:8888
    environment:
      ENCRYPT_KEY: IMSYMMETRIC
  oauth2server:
    image: liemmn/dxc-oauth2-server:microservices
    ports:
    - 9999:9999
  subscriptionservice:
    image: liemmn/dxc-subscription-service:microservices
    ports:
    - 8080:8080
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://configserver:8888
      CONFIGSERVER_PORT: '8888'
      DATABASESERVER_PORT: '5432'
      ENCRYPT_KEY: IMSYMMETRIC