version: '2.1'
services:
  ssg:
    image: caapim/microgateway:1.0.00
    ports:
    - 8443:8443
    env_file:
    - ./apigw/core.env
    - ./apigw/license-agreement.env
    - ./apigw/license.env
    - ./apigw/certificates.env
    - ./apigw/otk.env
    - ./apigw/jwt.env
    - ./apigw/feature-flags.env
    - ./apigw/solutionkits/policysdk.env
    environment:
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      SSG_SSL_KEY: MIIJ4QIBAzCCCacGCSqGSIb3DQEHAaCCCZgEggmUMIIJkDCCBEcGCSqGSIb3DQEHBqCCBDgwggQ0AgEAMIIELQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIi53V0I6c4z0CAggAgIIEAPyvqx+A1dedFnGawkc8pYG4OP7yyZJhVH6vjisjnUxHFXaQer5QObnk5rJmikuaSjaDsYNp39l8Gh35nMuD5Hc8q7gWaQHmtWDfGZgoFo3edgk2+e/YztyoO6rAOYyhoy72wiVU988W1dbZvY6/gK0+1i65e2YNY/0bQM5CJDPJvszyWfCUU4Cb1LX3dQJuemZj8foy+SpRVP3+R0kgB1SEEHnyNsbgV/vRQbpHFjYLt/IdFGIvURJRO42iq2lLaTtlMII0sOT9kqFkd4454tW7QQdjd8/Nsctny+wfFhABJAa5F2NHBHP77cvgfkmXNFqI1ileKP0JMx0pDtQeKwzIitjN77bdd5j/vL43EF6Ry5VKpFzZFjThj6fcIsDHtcUbbxeVPO9MEB5Ee+4qXh3va9d7zD5x0Hn/RGGqQtgD2B5ILA0FXNjPv4mJaIcHbWhTZlB8RO23U/82iEH7Cks11NO4inaAxr3b3dpyoN6JrpVEwVIW2GSxqSE09X9nIn/6xYmxWjWbuFSa++DBrCqsQY8sliU2KC9tbmebNS5eHr+16/44rQ3TBy0OFI3rLwk74eZje5sXxiBzHmWXk0u9iC2sZdDzk8KzO/WmOrvr0Q5AmKzDcRBodv/7r+4zQjhpRhY+en58hHaHkWpJ7deWtaU3rwkjly3UZlJurSYqgOqbQlFg6/O5elXx2x4ndAQds+pDC3tJlIzNssR4CFwInkU32xZP8B+KvavXjlNEi+qMwVO+brOgbTDjtW9ovZHVd3RHA+VeaR89FWjH9sgk2oJmtkSuRjgD4w1A/tzk62YlCcrgT6J4rjYya5O6v/JbMNo8r+/iGEgf++bUGW9VIEjJAk6KBe1fVRI4TYpYWBHczQxjKpPhKYi+S5pDEZdPVdXSKXvrzvkTj44Xast/3yKMWMvKIAxJukx36KjYcGYIByVIS0BEhQg2ON/XUqUW6+ywk+2avwIR87wnpjBRAGITrW/CJUaQmTPm15f8ZoWtf4m0vlc+YZ0tSHbaUzDksdKhBu2bHseAjgi9khLy4TEdwVEYDL54Dl4FF1wqdnNM6BCbMzfYj9UI+PpLIWIPwtp+SoRJlHBuFGc8xNPjAXDwF/NW/s7DHUkXflMy5BY36HTMhmo+zbiZsFr6vNe36hEANpJNtGd755LPMjWjuBQkclMhUa4XAOHF/zYX3w/aaJd3X0mzn40IettoDEJ5rC7WEYiWeBjpSIWUVJ62hDitDx69eJc8arDbIwHEorEMJiNDffBOReksrZ69bSJi1ANXuhXk8VNKGuDFH81vjJJmaXTQyXBxHP32loJu6sF/cIvxOHSEOnHvNEWTW2c0Xq1TKPXUDyHvmp90accwggVBBgkqhkiG9w0BBwGgggUyBIIFLjCCBSowggUmBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQI0iqoDeBwom8CAggABIIEyAAiKm9ijDAbEQJ2RQnTU4wRxt8cnF7+LqoaSh/aREOuxpeWffjOCeTijOMFd3j0Qf3gm8VZkIqYxDvu66BQt1+Qahn+98TXdRew2EjDeDBsOXZSk9Qp3TESvq2TUzuRKqBoyOFauMCxvelkr60pMYN3awgnWTBVyJ74kNyykjVsuxff1TPIPotqKmneHqqkgoIw+BPKit3BSSTcG5ij/cBFk+6ngaNU9+9lBMsddpvUJ5yXRxqDYS08ekrUL/wRl9GqMT7zidpTWTHzD+23mRZMJcU8Vm46c5hNrYU1RyhFcbAAMR+PasKbJA0gOPwxOZyHnu30Box6xU1BWoy+nAHJ17/t2iQf3mj22cQ996GhkEIjXzcgxLHqCjNAkf721Rz0K69+m8B3iysi/U5jtv2gYWs86Vug4kJbEhbyDZgO0lyxIO30y6BUPOLLH4Ui1XWd/BvPDzV+FHIht/G/WN11KUtI6LASpjPB4mIBhTZntijTo677h2mQzgM9mnizGmWbtJBzn5bnWG7p68iIYedF8Mp6YAdUh+eTT9I3DLz5JOrCb4/FA4x3Txy0AlKIEokkzoTOGNlgCPt1Kf5Fkubm5Ls5htX5Y3Hi9u2njIrSuBfJyVvjJzcMgNd660p8vWmOJm58CEdCNLACuASMyYa1GFhbZw5JT9l+SVx8n0V8zOEJT1FDVQbchLZS/nW8s6EZE/YpFR+qQ/J8RZWKv2JYwqE9CAiwEO4Xmv2ALQTGDNyyBuJpU0HoNvczb3EzJZXWVXTy2D/DViCyXymzlz2xKOZVSOYRwLaiCzZ83vIY5ct5XXNWPmJBxWHfWBU+UU+arBNMoO6hh4UiAhPYLt5FrypAAgMks5uzvnBRs8nnW0whPalr/kaGflr63fVTku1qrQcXlO0/RncRNAnHTqWCOzYVnEcGVKPKjTT7T/MboEj3U/6Wx8gwhTzJSXuAGZnToU3KAcI6MrR6onhL91pZni0lZsSj2/eUCxU4B5fbAa468C6YY0O4leccvy4pvrBkowGqiCUscftCIQcBryfcCDR2Z3x8xX/KKJ+6+ESIMmFAHJ9vBzj24sPfBsKSswfTKFj5TE6FkflvvRnseb/sPTzBTogv2gqS9dPPTJt+CrG9nVY48vtMQ3ECw+1yaOh0iut4atEyYk5vCDyflGbgiPCeClKqq66O9KMSnhJuMvWe1TnnitP4FRJl0X49wU0TrYzcewmO83mKVIwa77jP/wSNsXq1EudHr8+W0m0NgRmPfsAPvGDagBcBeVOPrM8iGmjB1C0EBIVLmh4GNNQHtnpcM++xq4eRGf/6xdNdXvCgGB0vP3BfJq8DvRBM1suW6sfaPpqbUE+MUGr9Jcs7ttiaEzgrXGQPLlhXM/35SmtXjeSc5yoLc9uq1FJKMisLVMcO/DYaIVcShuPmRMbNt7UPM6B68PCGwHu6vVGPwXeGpGr0ZanLM84mSPCzFTFpS6hduVFA4kL6UfFpUXxWB94NPc1O0QOb+YabwRgJpEKyA/Dkqma1ZQjAuv1xDPpDAzdW+exLrUetp00mmoZ2uDxcbvLFFHIV0hcNKhDwJPn8iiYdnLZk8sh+gxVC4ysuUXJL+LdDj7yD2QaLXbYwu06TjiXV4DElMCMGCSqGSIb3DQEJFTEWBBQAK6j3Gs7RFxNTsrBF/eL0vEmebTAxMCEwCQYFKw4DAhoFAAQUh9UgpvRkzPRkGC6wuI9Lim2KgxIECH3RZbUOQx5AAgIIAA==
      SSG_SSL_KEY_PASS: ""
      SSG_INTERNAL_SERVICES: "restman"
      QUICKSTART_REST_MODE: 'true'
      QUICKSTART_REPOSITORY_TYPE: db
      QUICKSTART_REPOSITORY_DB_TYPE: postgresql
      QUICKSTART_REPOSITORY_DB_HOST: database
      QUICKSTART_REPOSITORY_DB_PORT: '5432'
      QUICKSTART_REPOSITORY_DB_NAME: microservicedb
      QUICKSTART_REPOSITORY_DB_USER: postgres
      QUICKSTART_REPOSITORY_DB_PASSWORD: 7layer
    depends_on:
      database:
        condition: service_healthy
  database:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    ports:
    - 5432:5432
    volumes:
    - ./apigw/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: microservicedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7layer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
  configserver:
    image: liemmn/dxc-config-server:microservices
    ports:
    - 8888:8888
    environment:
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
  oauth2server:
    image: liemmn/dxc-oauth2-server:microservices
    ports:
    - 9999:9999
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
  subscriptionservice:
    image: liemmn/dxc-subscription-service:microservices
    ports:
    - 8889:8889
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://configserver:8888
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8889/health"]
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy