version: '2.1'
services:
  microdb-mysql:
    image: mysql:5.7
    mem_limit: 512m
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7layer
      MYSQL_DATABASE: microservicedb
    healthcheck:
      test: /usr/bin/mysql --user=root --password=7layer --execute "SHOW DATABASES;"
      interval: 10s
      timeout: 10s
  microbus-zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  microbus-kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=microbus-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  oauth2-service:
    image: liemmn/dxc-oauth2-server:microservices
    ports:
      - 9999:9999
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
volumes:
  db-volume:
