INSERT INTO movie (id, title, genre, price) VALUES (1, 'Terminator 2', 'Action', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (2, 'The God Father', 'Drama', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (3, 'Gladiator', 'Drama', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (4,'Jaws', 'Action', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (5,'Jurassic Park', 'Scifi', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (6,'Casablanca', 'Romance', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (7,'Psycho', 'Horror', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (8, 'Titanic', 'Drama', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (9, 'Saving Private Ryan', 'Drama', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (10,'Braveheart', 'Drama', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (11,'Lord of the Rings', 'Scifi', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (12,'The God Father Part II', 'Action', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (13,'West Side Story', 'Romance', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (14,'Doctor Zhivago', 'Romance', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (15,'The Shining', 'Horror', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (16,'The Matrix', 'Action', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (17,'Star Wars', 'Scifi', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (18,'Anchorman', 'Comedy', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (19,'American Pie', 'Comedy', 19.95);
INSERT INTO movie (id, title, genre, price) VALUES (20,'Beverly Hills Cops', 'Comedy', 19.95);