---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  annotations:
    description: Configuration service.
spec:
  selector:
    tier: service
    app: config
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: config-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: service
      app: config
  template:
    metadata:
      labels:
        tier: service
        app: config
    spec:
      containers:
      - name: config
        image: liemmn/dxc-config-server:microservices
        imagePullPolicy: Always
        ports:
          - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 5
