version: '2.1'
services:
  config-service:
    image: liemmn/dxc-config-server:microservices
    ports:
    - 8888:8888
    environment:
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"] 
  subscription-service:
    image: liemmn/dxc-subscription-service:microservices
    ports:
    - 8889:8889
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://config-service:8888
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8889/health"]
    depends_on:
      config-service:
         condition: service_healthy
  billing-service:
    image: liemmn/dxc-billing-service:microservices
    ports:
    - 8890:8890
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://config-service:8888
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8890/health"]
    depends_on:
      config-service:
         condition: service_healthy
  apigw-service:
    image: liemmn/dxc-zuul-server:microservices
    ports:
    - 8080:8080
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://config-service:8888
      ENCRYPT_KEY: IMSYMMETRIC 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    depends_on:
      config-service:
         condition: service_healthy