version: '2.1'
services:
  microdb-mysql:
    image: percona/percona-server:5.7
    ports:
    - 3306:3306
    volumes:
    - mysql-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7layer
      MYSQL_DATABASE: microservicedb
    healthcheck:
      test: /usr/bin/mysql --user=root --password=7layer --execute "SHOW DATABASES;"
      interval: 10s
      timeout: 10s
  eventing-rabbitmq-ha:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - 15672:15672
      - 5672:5672
  oauth2-service:
    image: liemmn/dxc-oauth2-server:microservices
    ports:
    - 9999:9999
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
  config-service:
    image: liemmn/dxc-config-server:microservices
    ports:
    - 8888:8888
    environment:
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"] 
  subscription-service:
    image: liemmn/dxc-subscription-service:microservices
    ports:
    - 8889:8889
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://config-service:8888
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8889/health"]
    depends_on:
      config-service:
         condition: service_healthy
  billing-service:
    image: liemmn/dxc-billing-service:microservices
    ports:
    - 8890:8890
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://config-service:8888
      ENCRYPT_KEY: IMSYMMETRIC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8890/health"]
    depends_on:
      config-service:
         condition: service_healthy
  apigw-service:
    image: liemmn/dxc-zuul-server:microservices
    ports:
    - 8080:8080
    environment:
      PROFILE: docker
      CONFIGSERVER_URI: http://config-service:8888
      ENCRYPT_KEY: IMSYMMETRIC 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    depends_on:
      config-service:
         condition: service_healthy
volumes:
  mysql-volume:
