server:
  port: 8890
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: billingTopic
          content-type: application/json
          group: billingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
logging:
  level:
    org.apache.kafka: WARN